# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6239030c56ac90d0d0a772393ff871e865cc53226195ed4e92489e3f9768a92e0e264d675f60bb076d4ca2d88417203329fb9b9e9310c913724aaff710733e25

test:
  secret_key_base: 5bd2629f9c685dde40f67c8c18472b89b1daaebe97f61490347ccd27161160706359770a537e4f996fa4feb99d54619f1e8a5f6886ed9ba1e3e08f4cd36bfaff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
